debian/extra/icon/mc.xpm usr/share/pixmaps
debian/lintian/mc usr/share/lintian/overrides
etc/mc/*
usr/bin/mc*
usr/lib/mc/extfs.d/*
usr/lib/mc/fish/*
usr/lib/mc/mc*sh usr/share/mc/bin
usr/share/locale/*
usr/share/man/es/*
usr/share/man/hu/*
usr/share/man/it/*
usr/share/man/man1/*
usr/share/man/pl/*
usr/share/man/ru/*
usr/share/man/sr/*
usr/share/mc/help/*
usr/share/mc/hints/*
usr/share/mc/mc.*
usr/share/mc/skins/*.ini
usr/share/mc/syntax/*.syntax
usr/share/mc/syntax/Syntax
